USE [aim1]
GO
ALTER VIEW [item].[vw1] AS
	select 
	id as PrimaryKey,
	null as ParentFolderId,
	ChildIndex,
	CreatedDateTime,
	LastModifiedDateTime,
	StartDateTime,
	EndDateTime,
	FinishDateTime,
	lower(uid)uid,
	secret,
	detailID,
	masterID,
	[item].[getAttributeData] (id,'Master') as idx,
	id AS itemID,
	hostID,
	NULL as nr,
	null as sourceID,
	keyID,
	srcID,
	null as inherit,
	inheritedID,
	null as fromID,
	null as toID,
	ownerID,
	userID,
	[item].classId(id) classID,
	Tag,
	null as tagname,
	keyname,
	null as UniqueKey,
	name,
	[item].[getattributevalue](id, 'Title') title,
	header1 description,
	header2 subject,
	summary,
	null as createdDT,
	null as modifiedDT,
	null as startDT,
	null as endDT,
	null as finishDT,
	null as indexDT,
	null as www,
	state,
	null as categorie,
	null as selected,
	groupname,
	files,
	null as msgCnt,
	hasChildren,
	null as geolocatie,
	location,
	createdByID,
	null as modifiedByID,
	null as cp,
	null as discount,
	null as msrp,
	null as findtext,
	null as stock,
	null as readID,
	null as writeID,
	filterfields,
	null as childClassNr,
	null as ClassNr,
	null as activeCnt,
	null as itemConfig,
	null as value
	from item.dt 
	where deleteddatetime is null
GO
